language: php

php:
    - 7.1
    - 7.2
    - 7.3

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

install:
    - composer install

script:
    - vendor/bin/phpunit
    - vendor/bin/phpcs -n src tests
