language: php

php:
    - 7.0
    - 7.1

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

install:
    - composer self-update && composer --version

script:
    - vendor/bin/phpunit
